"""Domain contracts for Code Review Agent."""

from codereviewer.domain.enums import (
    Confidence,
    FindingSource,
    ProviderKind,
    ReviewSourceKind,
    ReviewStage,
    Severity,
)
from codereviewer.domain.errors import (
    BudgetExceededError,
    CodeReviewerError,
    LLMProviderError,
    LLMResponseParseError,
    ProviderResolutionError,
    ToolExecutionError,
    ToolRegistrationError,
    UnsupportedProviderError,
)
from codereviewer.domain.models import (
    BudgetSnapshot,
    EvidenceRef,
    Finding,
    LLMReviewResult,
    PipelineResult,
    ReviewCheckpoint,
    ReviewRequest,
    ReviewSnapshot,
    ReviewTrace,
    RuleSpec,
    ToolResult,
    ToolSpec,
    TraceEvent,
)

__all__ = [
    "BudgetSnapshot",
    "BudgetExceededError",
    "CodeReviewerError",
    "Confidence",
    "EvidenceRef",
    "Finding",
    "FindingSource",
    "LLMProviderError",
    "LLMResponseParseError",
    "LLMReviewResult",
    "PipelineResult",
    "ProviderKind",
    "ProviderResolutionError",
    "ReviewCheckpoint",
    "ReviewRequest",
    "ReviewSnapshot",
    "ReviewTrace",
    "ReviewSourceKind",
    "ReviewStage",
    "RuleSpec",
    "Severity",
    "ToolExecutionError",
    "ToolRegistrationError",
    "ToolResult",
    "ToolSpec",
    "TraceEvent",
    "UnsupportedProviderError",
]
